#############################################################################
# Makefile for building: myHomework5Directory
# Generated by qmake (2.01a) (Qt 4.6.2) on: Thu Apr 26 02:47:07 2012
# Project:  myHomework5Directory.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile myHomework5Directory.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = bubble.cpp \
		bubbleBeam.cpp \
		bubbleBullet.cpp \
		bubbleLightning.cpp \
		bubblePoop.cpp \
		game.cpp \
		gameWindow.cpp \
		level1.cpp \
		level2.cpp \
		level3.cpp \
		level4.cpp \
		main.cpp \
		monster.cpp \
		monsterBoss.cpp \
		monsterBull.cpp \
		monsterLaser.cpp \
		monsterRobot.cpp \
		monsterSkeleton.cpp \
		player.cpp \
		powerup.cpp \
		powerupCandy.cpp \
		powerupDiamonds.cpp \
		powerupLife.cpp \
		powerupLightning.cpp \
		powerupPoison.cpp \
		powerupSkates.cpp moc_game.cpp \
		moc_gameWindow.cpp
OBJECTS       = bubble.o \
		bubbleBeam.o \
		bubbleBullet.o \
		bubbleLightning.o \
		bubblePoop.o \
		game.o \
		gameWindow.o \
		level1.o \
		level2.o \
		level3.o \
		level4.o \
		main.o \
		monster.o \
		monsterBoss.o \
		monsterBull.o \
		monsterLaser.o \
		monsterRobot.o \
		monsterSkeleton.o \
		player.o \
		powerup.o \
		powerupCandy.o \
		powerupDiamonds.o \
		powerupLife.o \
		powerupLightning.o \
		powerupPoison.o \
		powerupSkates.o \
		moc_game.o \
		moc_gameWindow.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		myHomework5Directory.pro
QMAKE_TARGET  = myHomework5Directory
DESTDIR       = 
TARGET        = myHomework5Directory

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: myHomework5Directory.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile myHomework5Directory.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile myHomework5Directory.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/myHomework5Directory1.0.0 || $(MKDIR) .tmp/myHomework5Directory1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/myHomework5Directory1.0.0/ && $(COPY_FILE) --parents bubble.h bubbleBeam.h bubbleBullet.h bubbleLightning.h bubblePoop.h game.h gameWindow.h level1.h level2.h level3.h level4.h monster.h monsterBoss.h monsterBull.h monsterLaser.h monsterRobot.h monsterSkeleton.h player.h powerup.h powerupCandy.h powerupDiamonds.h powerupLife.h powerupLightning.h powerupPoison.h powerupSkates.h .tmp/myHomework5Directory1.0.0/ && $(COPY_FILE) --parents bubble.cpp bubbleBeam.cpp bubbleBullet.cpp bubbleLightning.cpp bubblePoop.cpp game.cpp gameWindow.cpp level1.cpp level2.cpp level3.cpp level4.cpp main.cpp monster.cpp monsterBoss.cpp monsterBull.cpp monsterLaser.cpp monsterRobot.cpp monsterSkeleton.cpp player.cpp powerup.cpp powerupCandy.cpp powerupDiamonds.cpp powerupLife.cpp powerupLightning.cpp powerupPoison.cpp powerupSkates.cpp .tmp/myHomework5Directory1.0.0/ && (cd `dirname .tmp/myHomework5Directory1.0.0` && $(TAR) myHomework5Directory1.0.0.tar myHomework5Directory1.0.0 && $(COMPRESS) myHomework5Directory1.0.0.tar) && $(MOVE) `dirname .tmp/myHomework5Directory1.0.0`/myHomework5Directory1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/myHomework5Directory1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_game.cpp moc_gameWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_game.cpp moc_gameWindow.cpp
moc_game.cpp: player.h \
		bubble.h \
		monster.h \
		monsterBull.h \
		monsterSkeleton.h \
		monsterRobot.h \
		monsterLaser.h \
		bubbleBeam.h \
		bubblePoop.h \
		bubbleBullet.h \
		powerup.h \
		powerupCandy.h \
		powerupSkates.h \
		powerupPoison.h \
		powerupLightning.h \
		bubbleLightning.h \
		powerupDiamonds.h \
		powerupLife.h \
		monsterBoss.h \
		level1.h \
		level2.h \
		level3.h \
		level4.h \
		game.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) game.h -o moc_game.cpp

moc_gameWindow.cpp: game.h \
		player.h \
		bubble.h \
		monster.h \
		monsterBull.h \
		monsterSkeleton.h \
		monsterRobot.h \
		monsterLaser.h \
		bubbleBeam.h \
		bubblePoop.h \
		bubbleBullet.h \
		powerup.h \
		powerupCandy.h \
		powerupSkates.h \
		powerupPoison.h \
		powerupLightning.h \
		bubbleLightning.h \
		powerupDiamonds.h \
		powerupLife.h \
		monsterBoss.h \
		level1.h \
		level2.h \
		level3.h \
		level4.h \
		gameWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) gameWindow.h -o moc_gameWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

bubble.o: bubble.cpp bubble.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bubble.o bubble.cpp

bubbleBeam.o: bubbleBeam.cpp bubbleBeam.h \
		bubble.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bubbleBeam.o bubbleBeam.cpp

bubbleBullet.o: bubbleBullet.cpp bubbleBullet.h \
		bubble.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bubbleBullet.o bubbleBullet.cpp

bubbleLightning.o: bubbleLightning.cpp bubbleLightning.h \
		bubble.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bubbleLightning.o bubbleLightning.cpp

bubblePoop.o: bubblePoop.cpp bubblePoop.h \
		bubble.h \
		bubbleBeam.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bubblePoop.o bubblePoop.cpp

game.o: game.cpp game.h \
		player.h \
		bubble.h \
		monster.h \
		monsterBull.h \
		monsterSkeleton.h \
		monsterRobot.h \
		monsterLaser.h \
		bubbleBeam.h \
		bubblePoop.h \
		bubbleBullet.h \
		powerup.h \
		powerupCandy.h \
		powerupSkates.h \
		powerupPoison.h \
		powerupLightning.h \
		bubbleLightning.h \
		powerupDiamonds.h \
		powerupLife.h \
		monsterBoss.h \
		level1.h \
		level2.h \
		level3.h \
		level4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game.o game.cpp

gameWindow.o: gameWindow.cpp game.h \
		player.h \
		bubble.h \
		monster.h \
		monsterBull.h \
		monsterSkeleton.h \
		monsterRobot.h \
		monsterLaser.h \
		bubbleBeam.h \
		bubblePoop.h \
		bubbleBullet.h \
		powerup.h \
		powerupCandy.h \
		powerupSkates.h \
		powerupPoison.h \
		powerupLightning.h \
		bubbleLightning.h \
		powerupDiamonds.h \
		powerupLife.h \
		monsterBoss.h \
		level1.h \
		level2.h \
		level3.h \
		level4.h \
		gameWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gameWindow.o gameWindow.cpp

level1.o: level1.cpp level1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o level1.o level1.cpp

level2.o: level2.cpp level2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o level2.o level2.cpp

level3.o: level3.cpp level3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o level3.o level3.cpp

level4.o: level4.cpp level4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o level4.o level4.cpp

main.o: main.cpp game.h \
		player.h \
		bubble.h \
		monster.h \
		monsterBull.h \
		monsterSkeleton.h \
		monsterRobot.h \
		monsterLaser.h \
		bubbleBeam.h \
		bubblePoop.h \
		bubbleBullet.h \
		powerup.h \
		powerupCandy.h \
		powerupSkates.h \
		powerupPoison.h \
		powerupLightning.h \
		bubbleLightning.h \
		powerupDiamonds.h \
		powerupLife.h \
		monsterBoss.h \
		level1.h \
		level2.h \
		level3.h \
		level4.h \
		gameWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

monster.o: monster.cpp monster.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o monster.o monster.cpp

monsterBoss.o: monsterBoss.cpp monsterBoss.h \
		monster.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o monsterBoss.o monsterBoss.cpp

monsterBull.o: monsterBull.cpp monsterBull.h \
		monster.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o monsterBull.o monsterBull.cpp

monsterLaser.o: monsterLaser.cpp monsterLaser.h \
		monster.h \
		bubbleBeam.h \
		bubble.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o monsterLaser.o monsterLaser.cpp

monsterRobot.o: monsterRobot.cpp monsterRobot.h \
		monster.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o monsterRobot.o monsterRobot.cpp

monsterSkeleton.o: monsterSkeleton.cpp monsterSkeleton.h \
		monster.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o monsterSkeleton.o monsterSkeleton.cpp

player.o: player.cpp player.h \
		bubble.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

powerup.o: powerup.cpp powerup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o powerup.o powerup.cpp

powerupCandy.o: powerupCandy.cpp powerupCandy.h \
		powerup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o powerupCandy.o powerupCandy.cpp

powerupDiamonds.o: powerupDiamonds.cpp powerupDiamonds.h \
		powerup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o powerupDiamonds.o powerupDiamonds.cpp

powerupLife.o: powerupLife.cpp powerupLife.h \
		powerup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o powerupLife.o powerupLife.cpp

powerupLightning.o: powerupLightning.cpp powerupLightning.h \
		powerup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o powerupLightning.o powerupLightning.cpp

powerupPoison.o: powerupPoison.cpp powerupPoison.h \
		powerup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o powerupPoison.o powerupPoison.cpp

powerupSkates.o: powerupSkates.cpp powerupSkates.h \
		powerup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o powerupSkates.o powerupSkates.cpp

moc_game.o: moc_game.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_game.o moc_game.cpp

moc_gameWindow.o: moc_gameWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gameWindow.o moc_gameWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

